name: Enhanced Azure Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies with retry
        run: |
          # Try installing with pip, with retries for flaky packages
          for i in {1..3}; do
            pip install --no-cache-dir -r requirements.txt && break || {
              echo "Install attempt $i failed, retrying..."
              sleep 5
            }
          done

      - name: Verify installation
        run: |
          python -c "import fastapi, uvicorn, cloudinary, pymongo; print('✅ Core packages OK')"
          python -c "from psd_tools import PSDImage; print('✅ PSD tools OK')"
          python -c "from PIL import Image; print('✅ Pillow OK')"

      - name: Test app creation
        run: |
          # Set dummy environment variables for testing
          export CLOUDINARY_CLOUD_NAME=test
          export CLOUDINARY_API_KEY=test
          export CLOUDINARY_API_SECRET=test
          export MONGODB_CONNECTION_STRING=test
          python -c "from main import app; print('✅ App creation successful')"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !.git/
            !.github/
            !.venv/
            !venv/
            !__pycache__/
            !*.pyc
            !.env

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C361AD15B544A23A488423F95F5A867 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_93893363222F444BB769F345F0B73A2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_06EBD22786AD4ADF97DF4A40C37866C6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "converter"
          slot-name: "Production"
